services:
  postgres:
    image: postgres:16-alpine
    container_name: mavellium_db
    environment:
      POSTGRES_USER: mavellium
      POSTGRES_PASSWORD: mavellium123
      POSTGRES_DB: mavellium_fitec
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
